package com.fbee.modules.mybatis.model;

import java.util.Date;

public class DeliveryBoxInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.ORDER_SHARE_STAFF_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Integer orderShareStaffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.SHARE_ORDER_NO
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private String shareOrderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.ORDER_NO
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.SOURCE_TENANT_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Integer sourceTenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.TENANT_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Integer tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.STAFF_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.MATCHING_DEGREE
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Integer matchingDegree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.RETURN_REASON
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private String returnReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.HANDLE_RESULT
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private String handleResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.DELIVERY_DATE
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Date deliveryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.add_time
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.add_account
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private String addAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.modify_time
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.is_usable
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private String isUsable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column delivery_box_info.modify_account
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	private String modifyAccount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.ID
	 * @return  the value of delivery_box_info.ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.ID
	 * @param id  the value for delivery_box_info.ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.ORDER_SHARE_STAFF_ID
	 * @return  the value of delivery_box_info.ORDER_SHARE_STAFF_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Integer getOrderShareStaffId() {
		return orderShareStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.ORDER_SHARE_STAFF_ID
	 * @param orderShareStaffId  the value for delivery_box_info.ORDER_SHARE_STAFF_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setOrderShareStaffId(Integer orderShareStaffId) {
		this.orderShareStaffId = orderShareStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.SHARE_ORDER_NO
	 * @return  the value of delivery_box_info.SHARE_ORDER_NO
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getShareOrderNo() {
		return shareOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.SHARE_ORDER_NO
	 * @param shareOrderNo  the value for delivery_box_info.SHARE_ORDER_NO
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setShareOrderNo(String shareOrderNo) {
		this.shareOrderNo = shareOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.ORDER_NO
	 * @return  the value of delivery_box_info.ORDER_NO
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.ORDER_NO
	 * @param orderNo  the value for delivery_box_info.ORDER_NO
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.SOURCE_TENANT_ID
	 * @return  the value of delivery_box_info.SOURCE_TENANT_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Integer getSourceTenantId() {
		return sourceTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.SOURCE_TENANT_ID
	 * @param sourceTenantId  the value for delivery_box_info.SOURCE_TENANT_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setSourceTenantId(Integer sourceTenantId) {
		this.sourceTenantId = sourceTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.TENANT_ID
	 * @return  the value of delivery_box_info.TENANT_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Integer getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.TENANT_ID
	 * @param tenantId  the value for delivery_box_info.TENANT_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.STAFF_ID
	 * @return  the value of delivery_box_info.STAFF_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.STAFF_ID
	 * @param staffId  the value for delivery_box_info.STAFF_ID
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.MATCHING_DEGREE
	 * @return  the value of delivery_box_info.MATCHING_DEGREE
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Integer getMatchingDegree() {
		return matchingDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.MATCHING_DEGREE
	 * @param matchingDegree  the value for delivery_box_info.MATCHING_DEGREE
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setMatchingDegree(Integer matchingDegree) {
		this.matchingDegree = matchingDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.RETURN_REASON
	 * @return  the value of delivery_box_info.RETURN_REASON
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getReturnReason() {
		return returnReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.RETURN_REASON
	 * @param returnReason  the value for delivery_box_info.RETURN_REASON
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setReturnReason(String returnReason) {
		this.returnReason = returnReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.HANDLE_RESULT
	 * @return  the value of delivery_box_info.HANDLE_RESULT
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getHandleResult() {
		return handleResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.HANDLE_RESULT
	 * @param handleResult  the value for delivery_box_info.HANDLE_RESULT
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setHandleResult(String handleResult) {
		this.handleResult = handleResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.DELIVERY_DATE
	 * @return  the value of delivery_box_info.DELIVERY_DATE
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.DELIVERY_DATE
	 * @param deliveryDate  the value for delivery_box_info.DELIVERY_DATE
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.add_time
	 * @return  the value of delivery_box_info.add_time
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.add_time
	 * @param addTime  the value for delivery_box_info.add_time
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.add_account
	 * @return  the value of delivery_box_info.add_account
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getAddAccount() {
		return addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.add_account
	 * @param addAccount  the value for delivery_box_info.add_account
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.modify_time
	 * @return  the value of delivery_box_info.modify_time
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.modify_time
	 * @param modifyTime  the value for delivery_box_info.modify_time
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.is_usable
	 * @return  the value of delivery_box_info.is_usable
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getIsUsable() {
		return isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.is_usable
	 * @param isUsable  the value for delivery_box_info.is_usable
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column delivery_box_info.modify_account
	 * @return  the value of delivery_box_info.modify_account
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getModifyAccount() {
		return modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column delivery_box_info.modify_account
	 * @param modifyAccount  the value for delivery_box_info.modify_account
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}
}