package com.fbee.modules.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeliveryBoxInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public DeliveryBoxInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdIsNull() {
			addCriterion("ORDER_SHARE_STAFF_ID is null");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdIsNotNull() {
			addCriterion("ORDER_SHARE_STAFF_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdEqualTo(Integer value) {
			addCriterion("ORDER_SHARE_STAFF_ID =", value, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdNotEqualTo(Integer value) {
			addCriterion("ORDER_SHARE_STAFF_ID <>", value, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdGreaterThan(Integer value) {
			addCriterion("ORDER_SHARE_STAFF_ID >", value, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORDER_SHARE_STAFF_ID >=", value, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdLessThan(Integer value) {
			addCriterion("ORDER_SHARE_STAFF_ID <", value, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdLessThanOrEqualTo(Integer value) {
			addCriterion("ORDER_SHARE_STAFF_ID <=", value, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdIn(List<Integer> values) {
			addCriterion("ORDER_SHARE_STAFF_ID in", values, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdNotIn(List<Integer> values) {
			addCriterion("ORDER_SHARE_STAFF_ID not in", values, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_SHARE_STAFF_ID between", value1, value2, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andOrderShareStaffIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_SHARE_STAFF_ID not between", value1, value2, "orderShareStaffId");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoIsNull() {
			addCriterion("SHARE_ORDER_NO is null");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoIsNotNull() {
			addCriterion("SHARE_ORDER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO =", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO <>", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoGreaterThan(String value) {
			addCriterion("SHARE_ORDER_NO >", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO >=", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoLessThan(String value) {
			addCriterion("SHARE_ORDER_NO <", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoLessThanOrEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO <=", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoLike(String value) {
			addCriterion("SHARE_ORDER_NO like", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotLike(String value) {
			addCriterion("SHARE_ORDER_NO not like", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoIn(List<String> values) {
			addCriterion("SHARE_ORDER_NO in", values, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotIn(List<String> values) {
			addCriterion("SHARE_ORDER_NO not in", values, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoBetween(String value1, String value2) {
			addCriterion("SHARE_ORDER_NO between", value1, value2, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotBetween(String value1, String value2) {
			addCriterion("SHARE_ORDER_NO not between", value1, value2, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("ORDER_NO is null");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("ORDER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNoEqualTo(String value) {
			addCriterion("ORDER_NO =", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotEqualTo(String value) {
			addCriterion("ORDER_NO <>", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThan(String value) {
			addCriterion("ORDER_NO >", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_NO >=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThan(String value) {
			addCriterion("ORDER_NO <", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(String value) {
			addCriterion("ORDER_NO <=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLike(String value) {
			addCriterion("ORDER_NO like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotLike(String value) {
			addCriterion("ORDER_NO not like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIn(List<String> values) {
			addCriterion("ORDER_NO in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotIn(List<String> values) {
			addCriterion("ORDER_NO not in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoBetween(String value1, String value2) {
			addCriterion("ORDER_NO between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotBetween(String value1, String value2) {
			addCriterion("ORDER_NO not between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdIsNull() {
			addCriterion("SOURCE_TENANT_ID is null");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdIsNotNull() {
			addCriterion("SOURCE_TENANT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdEqualTo(Integer value) {
			addCriterion("SOURCE_TENANT_ID =", value, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdNotEqualTo(Integer value) {
			addCriterion("SOURCE_TENANT_ID <>", value, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdGreaterThan(Integer value) {
			addCriterion("SOURCE_TENANT_ID >", value, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("SOURCE_TENANT_ID >=", value, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdLessThan(Integer value) {
			addCriterion("SOURCE_TENANT_ID <", value, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdLessThanOrEqualTo(Integer value) {
			addCriterion("SOURCE_TENANT_ID <=", value, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdIn(List<Integer> values) {
			addCriterion("SOURCE_TENANT_ID in", values, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdNotIn(List<Integer> values) {
			addCriterion("SOURCE_TENANT_ID not in", values, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdBetween(Integer value1, Integer value2) {
			addCriterion("SOURCE_TENANT_ID between", value1, value2, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andSourceTenantIdNotBetween(Integer value1, Integer value2) {
			addCriterion("SOURCE_TENANT_ID not between", value1, value2, "sourceTenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNull() {
			addCriterion("TENANT_ID is null");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNotNull() {
			addCriterion("TENANT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTenantIdEqualTo(Integer value) {
			addCriterion("TENANT_ID =", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotEqualTo(Integer value) {
			addCriterion("TENANT_ID <>", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThan(Integer value) {
			addCriterion("TENANT_ID >", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("TENANT_ID >=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThan(Integer value) {
			addCriterion("TENANT_ID <", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThanOrEqualTo(Integer value) {
			addCriterion("TENANT_ID <=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIn(List<Integer> values) {
			addCriterion("TENANT_ID in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotIn(List<Integer> values) {
			addCriterion("TENANT_ID not in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdBetween(Integer value1, Integer value2) {
			addCriterion("TENANT_ID between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotBetween(Integer value1, Integer value2) {
			addCriterion("TENANT_ID not between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNull() {
			addCriterion("STAFF_ID is null");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNotNull() {
			addCriterion("STAFF_ID is not null");
			return (Criteria) this;
		}

		public Criteria andStaffIdEqualTo(Integer value) {
			addCriterion("STAFF_ID =", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotEqualTo(Integer value) {
			addCriterion("STAFF_ID <>", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThan(Integer value) {
			addCriterion("STAFF_ID >", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("STAFF_ID >=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThan(Integer value) {
			addCriterion("STAFF_ID <", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
			addCriterion("STAFF_ID <=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdIn(List<Integer> values) {
			addCriterion("STAFF_ID in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotIn(List<Integer> values) {
			addCriterion("STAFF_ID not in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdBetween(Integer value1, Integer value2) {
			addCriterion("STAFF_ID between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
			addCriterion("STAFF_ID not between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeIsNull() {
			addCriterion("MATCHING_DEGREE is null");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeIsNotNull() {
			addCriterion("MATCHING_DEGREE is not null");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeEqualTo(Integer value) {
			addCriterion("MATCHING_DEGREE =", value, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeNotEqualTo(Integer value) {
			addCriterion("MATCHING_DEGREE <>", value, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeGreaterThan(Integer value) {
			addCriterion("MATCHING_DEGREE >", value, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeGreaterThanOrEqualTo(Integer value) {
			addCriterion("MATCHING_DEGREE >=", value, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeLessThan(Integer value) {
			addCriterion("MATCHING_DEGREE <", value, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeLessThanOrEqualTo(Integer value) {
			addCriterion("MATCHING_DEGREE <=", value, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeIn(List<Integer> values) {
			addCriterion("MATCHING_DEGREE in", values, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeNotIn(List<Integer> values) {
			addCriterion("MATCHING_DEGREE not in", values, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeBetween(Integer value1, Integer value2) {
			addCriterion("MATCHING_DEGREE between", value1, value2, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andMatchingDegreeNotBetween(Integer value1, Integer value2) {
			addCriterion("MATCHING_DEGREE not between", value1, value2, "matchingDegree");
			return (Criteria) this;
		}

		public Criteria andReturnReasonIsNull() {
			addCriterion("RETURN_REASON is null");
			return (Criteria) this;
		}

		public Criteria andReturnReasonIsNotNull() {
			addCriterion("RETURN_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andReturnReasonEqualTo(String value) {
			addCriterion("RETURN_REASON =", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonNotEqualTo(String value) {
			addCriterion("RETURN_REASON <>", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonGreaterThan(String value) {
			addCriterion("RETURN_REASON >", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonGreaterThanOrEqualTo(String value) {
			addCriterion("RETURN_REASON >=", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonLessThan(String value) {
			addCriterion("RETURN_REASON <", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonLessThanOrEqualTo(String value) {
			addCriterion("RETURN_REASON <=", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonLike(String value) {
			addCriterion("RETURN_REASON like", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonNotLike(String value) {
			addCriterion("RETURN_REASON not like", value, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonIn(List<String> values) {
			addCriterion("RETURN_REASON in", values, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonNotIn(List<String> values) {
			addCriterion("RETURN_REASON not in", values, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonBetween(String value1, String value2) {
			addCriterion("RETURN_REASON between", value1, value2, "returnReason");
			return (Criteria) this;
		}

		public Criteria andReturnReasonNotBetween(String value1, String value2) {
			addCriterion("RETURN_REASON not between", value1, value2, "returnReason");
			return (Criteria) this;
		}

		public Criteria andHandleResultIsNull() {
			addCriterion("HANDLE_RESULT is null");
			return (Criteria) this;
		}

		public Criteria andHandleResultIsNotNull() {
			addCriterion("HANDLE_RESULT is not null");
			return (Criteria) this;
		}

		public Criteria andHandleResultEqualTo(String value) {
			addCriterion("HANDLE_RESULT =", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultNotEqualTo(String value) {
			addCriterion("HANDLE_RESULT <>", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultGreaterThan(String value) {
			addCriterion("HANDLE_RESULT >", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultGreaterThanOrEqualTo(String value) {
			addCriterion("HANDLE_RESULT >=", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultLessThan(String value) {
			addCriterion("HANDLE_RESULT <", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultLessThanOrEqualTo(String value) {
			addCriterion("HANDLE_RESULT <=", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultLike(String value) {
			addCriterion("HANDLE_RESULT like", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultNotLike(String value) {
			addCriterion("HANDLE_RESULT not like", value, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultIn(List<String> values) {
			addCriterion("HANDLE_RESULT in", values, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultNotIn(List<String> values) {
			addCriterion("HANDLE_RESULT not in", values, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultBetween(String value1, String value2) {
			addCriterion("HANDLE_RESULT between", value1, value2, "handleResult");
			return (Criteria) this;
		}

		public Criteria andHandleResultNotBetween(String value1, String value2) {
			addCriterion("HANDLE_RESULT not between", value1, value2, "handleResult");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateIsNull() {
			addCriterion("DELIVERY_DATE is null");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateIsNotNull() {
			addCriterion("DELIVERY_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateEqualTo(Date value) {
			addCriterion("DELIVERY_DATE =", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateNotEqualTo(Date value) {
			addCriterion("DELIVERY_DATE <>", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateGreaterThan(Date value) {
			addCriterion("DELIVERY_DATE >", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateGreaterThanOrEqualTo(Date value) {
			addCriterion("DELIVERY_DATE >=", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateLessThan(Date value) {
			addCriterion("DELIVERY_DATE <", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateLessThanOrEqualTo(Date value) {
			addCriterion("DELIVERY_DATE <=", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateIn(List<Date> values) {
			addCriterion("DELIVERY_DATE in", values, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateNotIn(List<Date> values) {
			addCriterion("DELIVERY_DATE not in", values, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateBetween(Date value1, Date value2) {
			addCriterion("DELIVERY_DATE between", value1, value2, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateNotBetween(Date value1, Date value2) {
			addCriterion("DELIVERY_DATE not between", value1, value2, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddAccountIsNull() {
			addCriterion("add_account is null");
			return (Criteria) this;
		}

		public Criteria andAddAccountIsNotNull() {
			addCriterion("add_account is not null");
			return (Criteria) this;
		}

		public Criteria andAddAccountEqualTo(String value) {
			addCriterion("add_account =", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotEqualTo(String value) {
			addCriterion("add_account <>", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountGreaterThan(String value) {
			addCriterion("add_account >", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountGreaterThanOrEqualTo(String value) {
			addCriterion("add_account >=", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLessThan(String value) {
			addCriterion("add_account <", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLessThanOrEqualTo(String value) {
			addCriterion("add_account <=", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLike(String value) {
			addCriterion("add_account like", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotLike(String value) {
			addCriterion("add_account not like", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountIn(List<String> values) {
			addCriterion("add_account in", values, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotIn(List<String> values) {
			addCriterion("add_account not in", values, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountBetween(String value1, String value2) {
			addCriterion("add_account between", value1, value2, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotBetween(String value1, String value2) {
			addCriterion("add_account not between", value1, value2, "addAccount");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("modify_time between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("modify_time not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andIsUsableIsNull() {
			addCriterion("is_usable is null");
			return (Criteria) this;
		}

		public Criteria andIsUsableIsNotNull() {
			addCriterion("is_usable is not null");
			return (Criteria) this;
		}

		public Criteria andIsUsableEqualTo(String value) {
			addCriterion("is_usable =", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotEqualTo(String value) {
			addCriterion("is_usable <>", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableGreaterThan(String value) {
			addCriterion("is_usable >", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableGreaterThanOrEqualTo(String value) {
			addCriterion("is_usable >=", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableLessThan(String value) {
			addCriterion("is_usable <", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableLessThanOrEqualTo(String value) {
			addCriterion("is_usable <=", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableLike(String value) {
			addCriterion("is_usable like", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotLike(String value) {
			addCriterion("is_usable not like", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableIn(List<String> values) {
			addCriterion("is_usable in", values, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotIn(List<String> values) {
			addCriterion("is_usable not in", values, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableBetween(String value1, String value2) {
			addCriterion("is_usable between", value1, value2, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotBetween(String value1, String value2) {
			addCriterion("is_usable not between", value1, value2, "isUsable");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIsNull() {
			addCriterion("modify_account is null");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIsNotNull() {
			addCriterion("modify_account is not null");
			return (Criteria) this;
		}

		public Criteria andModifyAccountEqualTo(String value) {
			addCriterion("modify_account =", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotEqualTo(String value) {
			addCriterion("modify_account <>", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountGreaterThan(String value) {
			addCriterion("modify_account >", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountGreaterThanOrEqualTo(String value) {
			addCriterion("modify_account >=", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLessThan(String value) {
			addCriterion("modify_account <", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLessThanOrEqualTo(String value) {
			addCriterion("modify_account <=", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLike(String value) {
			addCriterion("modify_account like", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotLike(String value) {
			addCriterion("modify_account not like", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIn(List<String> values) {
			addCriterion("modify_account in", values, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotIn(List<String> values) {
			addCriterion("modify_account not in", values, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountBetween(String value1, String value2) {
			addCriterion("modify_account between", value1, value2, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotBetween(String value1, String value2) {
			addCriterion("modify_account not between", value1, value2, "modifyAccount");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table delivery_box_info
	 * @mbggenerated  Mon Mar 27 16:19:34 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table delivery_box_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 02 11:55:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}