package com.fbee.modules.mybatis.model;

import java.util.Date;

public class OrderShareStaffInfo {
   
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.ORDER_NO
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.TENANT_ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private Integer tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.STAFF_ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.REMARK
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.add_time
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.add_account
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private String addAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.modify_time
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.STATUS
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.modify_account
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private String modifyAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_share_staff_info.is_usable
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	private String isUsable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.ID
	 * @return  the value of order_share_staff_info.ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.ID
	 * @param id  the value for order_share_staff_info.ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.ORDER_NO
	 * @return  the value of order_share_staff_info.ORDER_NO
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.ORDER_NO
	 * @param orderNo  the value for order_share_staff_info.ORDER_NO
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.TENANT_ID
	 * @return  the value of order_share_staff_info.TENANT_ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public Integer getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.TENANT_ID
	 * @param tenantId  the value for order_share_staff_info.TENANT_ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.STAFF_ID
	 * @return  the value of order_share_staff_info.STAFF_ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.STAFF_ID
	 * @param staffId  the value for order_share_staff_info.STAFF_ID
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.REMARK
	 * @return  the value of order_share_staff_info.REMARK
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.REMARK
	 * @param remark  the value for order_share_staff_info.REMARK
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.add_time
	 * @return  the value of order_share_staff_info.add_time
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.add_time
	 * @param addTime  the value for order_share_staff_info.add_time
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.add_account
	 * @return  the value of order_share_staff_info.add_account
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public String getAddAccount() {
		return addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.add_account
	 * @param addAccount  the value for order_share_staff_info.add_account
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.modify_time
	 * @return  the value of order_share_staff_info.modify_time
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.modify_time
	 * @param modifyTime  the value for order_share_staff_info.modify_time
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.STATUS
	 * @return  the value of order_share_staff_info.STATUS
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.STATUS
	 * @param status  the value for order_share_staff_info.STATUS
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.modify_account
	 * @return  the value of order_share_staff_info.modify_account
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public String getModifyAccount() {
		return modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.modify_account
	 * @param modifyAccount  the value for order_share_staff_info.modify_account
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_share_staff_info.is_usable
	 * @return  the value of order_share_staff_info.is_usable
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public String getIsUsable() {
		return isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_share_staff_info.is_usable
	 * @param isUsable  the value for order_share_staff_info.is_usable
	 * @mbggenerated  Thu Mar 02 13:38:38 CST 2017
	 */
	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}
	
}