package com.fbee.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrdersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public OrdersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("ORDER_NO is null");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("ORDER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNoEqualTo(String value) {
			addCriterion("ORDER_NO =", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotEqualTo(String value) {
			addCriterion("ORDER_NO <>", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThan(String value) {
			addCriterion("ORDER_NO >", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_NO >=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThan(String value) {
			addCriterion("ORDER_NO <", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(String value) {
			addCriterion("ORDER_NO <=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLike(String value) {
			addCriterion("ORDER_NO like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotLike(String value) {
			addCriterion("ORDER_NO not like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIn(List<String> values) {
			addCriterion("ORDER_NO in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotIn(List<String> values) {
			addCriterion("ORDER_NO not in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoBetween(String value1, String value2) {
			addCriterion("ORDER_NO between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotBetween(String value1, String value2) {
			addCriterion("ORDER_NO not between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNull() {
			addCriterion("TENANT_ID is null");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNotNull() {
			addCriterion("TENANT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTenantIdEqualTo(Integer value) {
			addCriterion("TENANT_ID =", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotEqualTo(Integer value) {
			addCriterion("TENANT_ID <>", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThan(Integer value) {
			addCriterion("TENANT_ID >", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("TENANT_ID >=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThan(Integer value) {
			addCriterion("TENANT_ID <", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThanOrEqualTo(Integer value) {
			addCriterion("TENANT_ID <=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIn(List<Integer> values) {
			addCriterion("TENANT_ID in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotIn(List<Integer> values) {
			addCriterion("TENANT_ID not in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdBetween(Integer value1, Integer value2) {
			addCriterion("TENANT_ID between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotBetween(Integer value1, Integer value2) {
			addCriterion("TENANT_ID not between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("MEMBER_ID is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("MEMBER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdEqualTo(Integer value) {
			addCriterion("MEMBER_ID =", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotEqualTo(Integer value) {
			addCriterion("MEMBER_ID <>", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThan(Integer value) {
			addCriterion("MEMBER_ID >", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("MEMBER_ID >=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThan(Integer value) {
			addCriterion("MEMBER_ID <", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
			addCriterion("MEMBER_ID <=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdIn(List<Integer> values) {
			addCriterion("MEMBER_ID in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotIn(List<Integer> values) {
			addCriterion("MEMBER_ID not in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdBetween(Integer value1, Integer value2) {
			addCriterion("MEMBER_ID between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
			addCriterion("MEMBER_ID not between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("AMOUNT =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("AMOUNT <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("AMOUNT >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AMOUNT >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("AMOUNT <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AMOUNT <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<BigDecimal> values) {
			addCriterion("AMOUNT in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<BigDecimal> values) {
			addCriterion("AMOUNT not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AMOUNT between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AMOUNT not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andOrderTimeIsNull() {
			addCriterion("ORDER_TIME is null");
			return (Criteria) this;
		}

		public Criteria andOrderTimeIsNotNull() {
			addCriterion("ORDER_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTimeEqualTo(Date value) {
			addCriterion("ORDER_TIME =", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeNotEqualTo(Date value) {
			addCriterion("ORDER_TIME <>", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeGreaterThan(Date value) {
			addCriterion("ORDER_TIME >", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ORDER_TIME >=", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeLessThan(Date value) {
			addCriterion("ORDER_TIME <", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeLessThanOrEqualTo(Date value) {
			addCriterion("ORDER_TIME <=", value, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeIn(List<Date> values) {
			addCriterion("ORDER_TIME in", values, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeNotIn(List<Date> values) {
			addCriterion("ORDER_TIME not in", values, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeBetween(Date value1, Date value2) {
			addCriterion("ORDER_TIME between", value1, value2, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderTimeNotBetween(Date value1, Date value2) {
			addCriterion("ORDER_TIME not between", value1, value2, "orderTime");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("ORDER_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("ORDER_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(String value) {
			addCriterion("ORDER_STATUS =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(String value) {
			addCriterion("ORDER_STATUS <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(String value) {
			addCriterion("ORDER_STATUS >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_STATUS >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(String value) {
			addCriterion("ORDER_STATUS <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(String value) {
			addCriterion("ORDER_STATUS <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLike(String value) {
			addCriterion("ORDER_STATUS like", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotLike(String value) {
			addCriterion("ORDER_STATUS not like", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<String> values) {
			addCriterion("ORDER_STATUS in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<String> values) {
			addCriterion("ORDER_STATUS not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(String value1, String value2) {
			addCriterion("ORDER_STATUS between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(String value1, String value2) {
			addCriterion("ORDER_STATUS not between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeIsNull() {
			addCriterion("SERVICE_ITEM_CODE is null");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeIsNotNull() {
			addCriterion("SERVICE_ITEM_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeEqualTo(String value) {
			addCriterion("SERVICE_ITEM_CODE =", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeNotEqualTo(String value) {
			addCriterion("SERVICE_ITEM_CODE <>", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeGreaterThan(String value) {
			addCriterion("SERVICE_ITEM_CODE >", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeGreaterThanOrEqualTo(String value) {
			addCriterion("SERVICE_ITEM_CODE >=", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeLessThan(String value) {
			addCriterion("SERVICE_ITEM_CODE <", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeLessThanOrEqualTo(String value) {
			addCriterion("SERVICE_ITEM_CODE <=", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeLike(String value) {
			addCriterion("SERVICE_ITEM_CODE like", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeNotLike(String value) {
			addCriterion("SERVICE_ITEM_CODE not like", value, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeIn(List<String> values) {
			addCriterion("SERVICE_ITEM_CODE in", values, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeNotIn(List<String> values) {
			addCriterion("SERVICE_ITEM_CODE not in", values, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeBetween(String value1, String value2) {
			addCriterion("SERVICE_ITEM_CODE between", value1, value2, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andServiceItemCodeNotBetween(String value1, String value2) {
			addCriterion("SERVICE_ITEM_CODE not between", value1, value2, "serviceItemCode");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNull() {
			addCriterion("STAFF_ID is null");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNotNull() {
			addCriterion("STAFF_ID is not null");
			return (Criteria) this;
		}

		public Criteria andStaffIdEqualTo(Integer value) {
			addCriterion("STAFF_ID =", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotEqualTo(Integer value) {
			addCriterion("STAFF_ID <>", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThan(Integer value) {
			addCriterion("STAFF_ID >", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("STAFF_ID >=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThan(Integer value) {
			addCriterion("STAFF_ID <", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
			addCriterion("STAFF_ID <=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdIn(List<Integer> values) {
			addCriterion("STAFF_ID in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotIn(List<Integer> values) {
			addCriterion("STAFF_ID not in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdBetween(Integer value1, Integer value2) {
			addCriterion("STAFF_ID between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
			addCriterion("STAFF_ID not between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andOrderSourceIsNull() {
			addCriterion("ORDER_SOURCE is null");
			return (Criteria) this;
		}

		public Criteria andOrderSourceIsNotNull() {
			addCriterion("ORDER_SOURCE is not null");
			return (Criteria) this;
		}

		public Criteria andOrderSourceEqualTo(String value) {
			addCriterion("ORDER_SOURCE =", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceNotEqualTo(String value) {
			addCriterion("ORDER_SOURCE <>", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceGreaterThan(String value) {
			addCriterion("ORDER_SOURCE >", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_SOURCE >=", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceLessThan(String value) {
			addCriterion("ORDER_SOURCE <", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceLessThanOrEqualTo(String value) {
			addCriterion("ORDER_SOURCE <=", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceLike(String value) {
			addCriterion("ORDER_SOURCE like", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceNotLike(String value) {
			addCriterion("ORDER_SOURCE not like", value, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceIn(List<String> values) {
			addCriterion("ORDER_SOURCE in", values, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceNotIn(List<String> values) {
			addCriterion("ORDER_SOURCE not in", values, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceBetween(String value1, String value2) {
			addCriterion("ORDER_SOURCE between", value1, value2, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderSourceNotBetween(String value1, String value2) {
			addCriterion("ORDER_SOURCE not between", value1, value2, "orderSource");
			return (Criteria) this;
		}

		public Criteria andOrderDepositIsNull() {
			addCriterion("ORDER_DEPOSIT is null");
			return (Criteria) this;
		}

		public Criteria andOrderDepositIsNotNull() {
			addCriterion("ORDER_DEPOSIT is not null");
			return (Criteria) this;
		}

		public Criteria andOrderDepositEqualTo(BigDecimal value) {
			addCriterion("ORDER_DEPOSIT =", value, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositNotEqualTo(BigDecimal value) {
			addCriterion("ORDER_DEPOSIT <>", value, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositGreaterThan(BigDecimal value) {
			addCriterion("ORDER_DEPOSIT >", value, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ORDER_DEPOSIT >=", value, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositLessThan(BigDecimal value) {
			addCriterion("ORDER_DEPOSIT <", value, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ORDER_DEPOSIT <=", value, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositIn(List<BigDecimal> values) {
			addCriterion("ORDER_DEPOSIT in", values, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositNotIn(List<BigDecimal> values) {
			addCriterion("ORDER_DEPOSIT not in", values, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ORDER_DEPOSIT between", value1, value2, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderDepositNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ORDER_DEPOSIT not between", value1, value2, "orderDeposit");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceIsNull() {
			addCriterion("ORDER_BALANCE is null");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceIsNotNull() {
			addCriterion("ORDER_BALANCE is not null");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceEqualTo(BigDecimal value) {
			addCriterion("ORDER_BALANCE =", value, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceNotEqualTo(BigDecimal value) {
			addCriterion("ORDER_BALANCE <>", value, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceGreaterThan(BigDecimal value) {
			addCriterion("ORDER_BALANCE >", value, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ORDER_BALANCE >=", value, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceLessThan(BigDecimal value) {
			addCriterion("ORDER_BALANCE <", value, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ORDER_BALANCE <=", value, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceIn(List<BigDecimal> values) {
			addCriterion("ORDER_BALANCE in", values, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceNotIn(List<BigDecimal> values) {
			addCriterion("ORDER_BALANCE not in", values, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ORDER_BALANCE between", value1, value2, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andOrderBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ORDER_BALANCE not between", value1, value2, "orderBalance");
			return (Criteria) this;
		}

		public Criteria andDepositDateIsNull() {
			addCriterion("DEPOSIT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andDepositDateIsNotNull() {
			addCriterion("DEPOSIT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andDepositDateEqualTo(Date value) {
			addCriterion("DEPOSIT_DATE =", value, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateNotEqualTo(Date value) {
			addCriterion("DEPOSIT_DATE <>", value, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateGreaterThan(Date value) {
			addCriterion("DEPOSIT_DATE >", value, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateGreaterThanOrEqualTo(Date value) {
			addCriterion("DEPOSIT_DATE >=", value, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateLessThan(Date value) {
			addCriterion("DEPOSIT_DATE <", value, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateLessThanOrEqualTo(Date value) {
			addCriterion("DEPOSIT_DATE <=", value, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateIn(List<Date> values) {
			addCriterion("DEPOSIT_DATE in", values, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateNotIn(List<Date> values) {
			addCriterion("DEPOSIT_DATE not in", values, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateBetween(Date value1, Date value2) {
			addCriterion("DEPOSIT_DATE between", value1, value2, "depositDate");
			return (Criteria) this;
		}

		public Criteria andDepositDateNotBetween(Date value1, Date value2) {
			addCriterion("DEPOSIT_DATE not between", value1, value2, "depositDate");
			return (Criteria) this;
		}

		public Criteria andIdepositOverIsNull() {
			addCriterion("IDEPOSIT_OVER is null");
			return (Criteria) this;
		}

		public Criteria andIdepositOverIsNotNull() {
			addCriterion("IDEPOSIT_OVER is not null");
			return (Criteria) this;
		}

		public Criteria andIdepositOverEqualTo(String value) {
			addCriterion("IDEPOSIT_OVER =", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverNotEqualTo(String value) {
			addCriterion("IDEPOSIT_OVER <>", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverGreaterThan(String value) {
			addCriterion("IDEPOSIT_OVER >", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverGreaterThanOrEqualTo(String value) {
			addCriterion("IDEPOSIT_OVER >=", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverLessThan(String value) {
			addCriterion("IDEPOSIT_OVER <", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverLessThanOrEqualTo(String value) {
			addCriterion("IDEPOSIT_OVER <=", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverLike(String value) {
			addCriterion("IDEPOSIT_OVER like", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverNotLike(String value) {
			addCriterion("IDEPOSIT_OVER not like", value, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverIn(List<String> values) {
			addCriterion("IDEPOSIT_OVER in", values, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverNotIn(List<String> values) {
			addCriterion("IDEPOSIT_OVER not in", values, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverBetween(String value1, String value2) {
			addCriterion("IDEPOSIT_OVER between", value1, value2, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIdepositOverNotBetween(String value1, String value2) {
			addCriterion("IDEPOSIT_OVER not between", value1, value2, "idepositOver");
			return (Criteria) this;
		}

		public Criteria andIsInterviewIsNull() {
			addCriterion("IS_INTERVIEW is null");
			return (Criteria) this;
		}

		public Criteria andIsInterviewIsNotNull() {
			addCriterion("IS_INTERVIEW is not null");
			return (Criteria) this;
		}

		public Criteria andIsInterviewEqualTo(String value) {
			addCriterion("IS_INTERVIEW =", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewNotEqualTo(String value) {
			addCriterion("IS_INTERVIEW <>", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewGreaterThan(String value) {
			addCriterion("IS_INTERVIEW >", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewGreaterThanOrEqualTo(String value) {
			addCriterion("IS_INTERVIEW >=", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewLessThan(String value) {
			addCriterion("IS_INTERVIEW <", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewLessThanOrEqualTo(String value) {
			addCriterion("IS_INTERVIEW <=", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewLike(String value) {
			addCriterion("IS_INTERVIEW like", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewNotLike(String value) {
			addCriterion("IS_INTERVIEW not like", value, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewIn(List<String> values) {
			addCriterion("IS_INTERVIEW in", values, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewNotIn(List<String> values) {
			addCriterion("IS_INTERVIEW not in", values, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewBetween(String value1, String value2) {
			addCriterion("IS_INTERVIEW between", value1, value2, "isInterview");
			return (Criteria) this;
		}

		public Criteria andIsInterviewNotBetween(String value1, String value2) {
			addCriterion("IS_INTERVIEW not between", value1, value2, "isInterview");
			return (Criteria) this;
		}

		public Criteria andPassViewDateIsNull() {
			addCriterion("PASS_VIEW_DATE is null");
			return (Criteria) this;
		}

		public Criteria andPassViewDateIsNotNull() {
			addCriterion("PASS_VIEW_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andPassViewDateEqualTo(Date value) {
			addCriterion("PASS_VIEW_DATE =", value, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateNotEqualTo(Date value) {
			addCriterion("PASS_VIEW_DATE <>", value, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateGreaterThan(Date value) {
			addCriterion("PASS_VIEW_DATE >", value, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateGreaterThanOrEqualTo(Date value) {
			addCriterion("PASS_VIEW_DATE >=", value, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateLessThan(Date value) {
			addCriterion("PASS_VIEW_DATE <", value, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateLessThanOrEqualTo(Date value) {
			addCriterion("PASS_VIEW_DATE <=", value, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateIn(List<Date> values) {
			addCriterion("PASS_VIEW_DATE in", values, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateNotIn(List<Date> values) {
			addCriterion("PASS_VIEW_DATE not in", values, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateBetween(Date value1, Date value2) {
			addCriterion("PASS_VIEW_DATE between", value1, value2, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andPassViewDateNotBetween(Date value1, Date value2) {
			addCriterion("PASS_VIEW_DATE not between", value1, value2, "passViewDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateIsNull() {
			addCriterion("BALANCE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andBalanceDateIsNotNull() {
			addCriterion("BALANCE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andBalanceDateEqualTo(Date value) {
			addCriterion("BALANCE_DATE =", value, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateNotEqualTo(Date value) {
			addCriterion("BALANCE_DATE <>", value, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateGreaterThan(Date value) {
			addCriterion("BALANCE_DATE >", value, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateGreaterThanOrEqualTo(Date value) {
			addCriterion("BALANCE_DATE >=", value, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateLessThan(Date value) {
			addCriterion("BALANCE_DATE <", value, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateLessThanOrEqualTo(Date value) {
			addCriterion("BALANCE_DATE <=", value, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateIn(List<Date> values) {
			addCriterion("BALANCE_DATE in", values, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateNotIn(List<Date> values) {
			addCriterion("BALANCE_DATE not in", values, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateBetween(Date value1, Date value2) {
			addCriterion("BALANCE_DATE between", value1, value2, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andBalanceDateNotBetween(Date value1, Date value2) {
			addCriterion("BALANCE_DATE not between", value1, value2, "balanceDate");
			return (Criteria) this;
		}

		public Criteria andIsLockIsNull() {
			addCriterion("IS_LOCK is null");
			return (Criteria) this;
		}

		public Criteria andIsLockIsNotNull() {
			addCriterion("IS_LOCK is not null");
			return (Criteria) this;
		}

		public Criteria andIsLockEqualTo(String value) {
			addCriterion("IS_LOCK =", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotEqualTo(String value) {
			addCriterion("IS_LOCK <>", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockGreaterThan(String value) {
			addCriterion("IS_LOCK >", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockGreaterThanOrEqualTo(String value) {
			addCriterion("IS_LOCK >=", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLessThan(String value) {
			addCriterion("IS_LOCK <", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLessThanOrEqualTo(String value) {
			addCriterion("IS_LOCK <=", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLike(String value) {
			addCriterion("IS_LOCK like", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotLike(String value) {
			addCriterion("IS_LOCK not like", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockIn(List<String> values) {
			addCriterion("IS_LOCK in", values, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotIn(List<String> values) {
			addCriterion("IS_LOCK not in", values, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockBetween(String value1, String value2) {
			addCriterion("IS_LOCK between", value1, value2, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotBetween(String value1, String value2) {
			addCriterion("IS_LOCK not between", value1, value2, "isLock");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddAccountIsNull() {
			addCriterion("add_account is null");
			return (Criteria) this;
		}

		public Criteria andAddAccountIsNotNull() {
			addCriterion("add_account is not null");
			return (Criteria) this;
		}

		public Criteria andAddAccountEqualTo(String value) {
			addCriterion("add_account =", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotEqualTo(String value) {
			addCriterion("add_account <>", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountGreaterThan(String value) {
			addCriterion("add_account >", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountGreaterThanOrEqualTo(String value) {
			addCriterion("add_account >=", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLessThan(String value) {
			addCriterion("add_account <", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLessThanOrEqualTo(String value) {
			addCriterion("add_account <=", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLike(String value) {
			addCriterion("add_account like", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotLike(String value) {
			addCriterion("add_account not like", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountIn(List<String> values) {
			addCriterion("add_account in", values, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotIn(List<String> values) {
			addCriterion("add_account not in", values, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountBetween(String value1, String value2) {
			addCriterion("add_account between", value1, value2, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotBetween(String value1, String value2) {
			addCriterion("add_account not between", value1, value2, "addAccount");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("modify_time between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("modify_time not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIsNull() {
			addCriterion("modify_account is null");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIsNotNull() {
			addCriterion("modify_account is not null");
			return (Criteria) this;
		}

		public Criteria andModifyAccountEqualTo(String value) {
			addCriterion("modify_account =", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotEqualTo(String value) {
			addCriterion("modify_account <>", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountGreaterThan(String value) {
			addCriterion("modify_account >", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountGreaterThanOrEqualTo(String value) {
			addCriterion("modify_account >=", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLessThan(String value) {
			addCriterion("modify_account <", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLessThanOrEqualTo(String value) {
			addCriterion("modify_account <=", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLike(String value) {
			addCriterion("modify_account like", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotLike(String value) {
			addCriterion("modify_account not like", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIn(List<String> values) {
			addCriterion("modify_account in", values, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotIn(List<String> values) {
			addCriterion("modify_account not in", values, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountBetween(String value1, String value2) {
			addCriterion("modify_account between", value1, value2, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotBetween(String value1, String value2) {
			addCriterion("modify_account not between", value1, value2, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoIsNull() {
			addCriterion("RESERVE_ORDER_NO is null");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoIsNotNull() {
			addCriterion("RESERVE_ORDER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoEqualTo(String value) {
			addCriterion("RESERVE_ORDER_NO =", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoNotEqualTo(String value) {
			addCriterion("RESERVE_ORDER_NO <>", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoGreaterThan(String value) {
			addCriterion("RESERVE_ORDER_NO >", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("RESERVE_ORDER_NO >=", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoLessThan(String value) {
			addCriterion("RESERVE_ORDER_NO <", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoLessThanOrEqualTo(String value) {
			addCriterion("RESERVE_ORDER_NO <=", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoLike(String value) {
			addCriterion("RESERVE_ORDER_NO like", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoNotLike(String value) {
			addCriterion("RESERVE_ORDER_NO not like", value, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoIn(List<String> values) {
			addCriterion("RESERVE_ORDER_NO in", values, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoNotIn(List<String> values) {
			addCriterion("RESERVE_ORDER_NO not in", values, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoBetween(String value1, String value2) {
			addCriterion("RESERVE_ORDER_NO between", value1, value2, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andReserveOrderNoNotBetween(String value1, String value2) {
			addCriterion("RESERVE_ORDER_NO not between", value1, value2, "reserveOrderNo");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("ORDER_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("ORDER_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeEqualTo(String value) {
			addCriterion("ORDER_TYPE =", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotEqualTo(String value) {
			addCriterion("ORDER_TYPE <>", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThan(String value) {
			addCriterion("ORDER_TYPE >", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_TYPE >=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThan(String value) {
			addCriterion("ORDER_TYPE <", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(String value) {
			addCriterion("ORDER_TYPE <=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLike(String value) {
			addCriterion("ORDER_TYPE like", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotLike(String value) {
			addCriterion("ORDER_TYPE not like", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIn(List<String> values) {
			addCriterion("ORDER_TYPE in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotIn(List<String> values) {
			addCriterion("ORDER_TYPE not in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeBetween(String value1, String value2) {
			addCriterion("ORDER_TYPE between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotBetween(String value1, String value2) {
			addCriterion("ORDER_TYPE not between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andMemberMobileIsNull() {
			addCriterion("MEMBER_MOBILE is null");
			return (Criteria) this;
		}

		public Criteria andMemberMobileIsNotNull() {
			addCriterion("MEMBER_MOBILE is not null");
			return (Criteria) this;
		}

		public Criteria andMemberMobileEqualTo(String value) {
			addCriterion("MEMBER_MOBILE =", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileNotEqualTo(String value) {
			addCriterion("MEMBER_MOBILE <>", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileGreaterThan(String value) {
			addCriterion("MEMBER_MOBILE >", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileGreaterThanOrEqualTo(String value) {
			addCriterion("MEMBER_MOBILE >=", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileLessThan(String value) {
			addCriterion("MEMBER_MOBILE <", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileLessThanOrEqualTo(String value) {
			addCriterion("MEMBER_MOBILE <=", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileLike(String value) {
			addCriterion("MEMBER_MOBILE like", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileNotLike(String value) {
			addCriterion("MEMBER_MOBILE not like", value, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileIn(List<String> values) {
			addCriterion("MEMBER_MOBILE in", values, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileNotIn(List<String> values) {
			addCriterion("MEMBER_MOBILE not in", values, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileBetween(String value1, String value2) {
			addCriterion("MEMBER_MOBILE between", value1, value2, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andMemberMobileNotBetween(String value1, String value2) {
			addCriterion("MEMBER_MOBILE not between", value1, value2, "memberMobile");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoIsNull() {
			addCriterion("SHARE_ORDER_NO is null");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoIsNotNull() {
			addCriterion("SHARE_ORDER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO =", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO <>", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoGreaterThan(String value) {
			addCriterion("SHARE_ORDER_NO >", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO >=", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoLessThan(String value) {
			addCriterion("SHARE_ORDER_NO <", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoLessThanOrEqualTo(String value) {
			addCriterion("SHARE_ORDER_NO <=", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoLike(String value) {
			addCriterion("SHARE_ORDER_NO like", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotLike(String value) {
			addCriterion("SHARE_ORDER_NO not like", value, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoIn(List<String> values) {
			addCriterion("SHARE_ORDER_NO in", values, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotIn(List<String> values) {
			addCriterion("SHARE_ORDER_NO not in", values, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoBetween(String value1, String value2) {
			addCriterion("SHARE_ORDER_NO between", value1, value2, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andShareOrderNoNotBetween(String value1, String value2) {
			addCriterion("SHARE_ORDER_NO not between", value1, value2, "shareOrderNo");
			return (Criteria) this;
		}

		public Criteria andBalanceOverIsNull() {
			addCriterion("BALANCE_OVER is null");
			return (Criteria) this;
		}

		public Criteria andBalanceOverIsNotNull() {
			addCriterion("BALANCE_OVER is not null");
			return (Criteria) this;
		}

		public Criteria andBalanceOverEqualTo(String value) {
			addCriterion("BALANCE_OVER =", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverNotEqualTo(String value) {
			addCriterion("BALANCE_OVER <>", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverGreaterThan(String value) {
			addCriterion("BALANCE_OVER >", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverGreaterThanOrEqualTo(String value) {
			addCriterion("BALANCE_OVER >=", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverLessThan(String value) {
			addCriterion("BALANCE_OVER <", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverLessThanOrEqualTo(String value) {
			addCriterion("BALANCE_OVER <=", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverLike(String value) {
			addCriterion("BALANCE_OVER like", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverNotLike(String value) {
			addCriterion("BALANCE_OVER not like", value, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverIn(List<String> values) {
			addCriterion("BALANCE_OVER in", values, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverNotIn(List<String> values) {
			addCriterion("BALANCE_OVER not in", values, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverBetween(String value1, String value2) {
			addCriterion("BALANCE_OVER between", value1, value2, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andBalanceOverNotBetween(String value1, String value2) {
			addCriterion("BALANCE_OVER not between", value1, value2, "balanceOver");
			return (Criteria) this;
		}

		public Criteria andIsUsableIsNull() {
			addCriterion("is_usable is null");
			return (Criteria) this;
		}

		public Criteria andIsUsableIsNotNull() {
			addCriterion("is_usable is not null");
			return (Criteria) this;
		}

		public Criteria andIsUsableEqualTo(String value) {
			addCriterion("is_usable =", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotEqualTo(String value) {
			addCriterion("is_usable <>", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableGreaterThan(String value) {
			addCriterion("is_usable >", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableGreaterThanOrEqualTo(String value) {
			addCriterion("is_usable >=", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableLessThan(String value) {
			addCriterion("is_usable <", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableLessThanOrEqualTo(String value) {
			addCriterion("is_usable <=", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableLike(String value) {
			addCriterion("is_usable like", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotLike(String value) {
			addCriterion("is_usable not like", value, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableIn(List<String> values) {
			addCriterion("is_usable in", values, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotIn(List<String> values) {
			addCriterion("is_usable not in", values, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableBetween(String value1, String value2) {
			addCriterion("is_usable between", value1, value2, "isUsable");
			return (Criteria) this;
		}

		public Criteria andIsUsableNotBetween(String value1, String value2) {
			addCriterion("is_usable not between", value1, value2, "isUsable");
			return (Criteria) this;
		}

		public Criteria andCancleReasonIsNull() {
			addCriterion("CANCLE_REASON is null");
			return (Criteria) this;
		}

		public Criteria andCancleReasonIsNotNull() {
			addCriterion("CANCLE_REASON is not null");
			return (Criteria) this;
		}

		public Criteria andCancleReasonEqualTo(String value) {
			addCriterion("CANCLE_REASON =", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonNotEqualTo(String value) {
			addCriterion("CANCLE_REASON <>", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonGreaterThan(String value) {
			addCriterion("CANCLE_REASON >", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonGreaterThanOrEqualTo(String value) {
			addCriterion("CANCLE_REASON >=", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonLessThan(String value) {
			addCriterion("CANCLE_REASON <", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonLessThanOrEqualTo(String value) {
			addCriterion("CANCLE_REASON <=", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonLike(String value) {
			addCriterion("CANCLE_REASON like", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonNotLike(String value) {
			addCriterion("CANCLE_REASON not like", value, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonIn(List<String> values) {
			addCriterion("CANCLE_REASON in", values, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonNotIn(List<String> values) {
			addCriterion("CANCLE_REASON not in", values, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonBetween(String value1, String value2) {
			addCriterion("CANCLE_REASON between", value1, value2, "cancleReason");
			return (Criteria) this;
		}

		public Criteria andCancleReasonNotBetween(String value1, String value2) {
			addCriterion("CANCLE_REASON not between", value1, value2, "cancleReason");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 28 17:26:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}