package com.fbee.modules.mybatis.model;

import java.util.Date;

public class OrderShareInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.ORDER_NO
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.TENANT_ID
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private Integer tenantId;

    /**
     * 表：order_share_info
     * 字段：SHARE_ID
     * 注释：分享人id
     *
     * @mbggenerated
     */
    private Integer shareId;

    /**
     * 表：order_share_info
     * 字段：ORDER_NAME
     * 注释：订单名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.SHARE_ID
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.AGE_REQUIREMENT
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String ageRequirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.SALARY_SITUATION
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String salarySituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.REMARK
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.STATUS
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.SINGLE_REWARD
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String singleReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.add_time
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.add_account
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.modify_time
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.modify_account
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_share_info.is_usable
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    private String isUsable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.ORDER_NO
     *
     * @return the value of order_share_info.ORDER_NO
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.ORDER_NO
     *
     * @param orderNo the value for order_share_info.ORDER_NO
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.TENANT_ID
     *
     * @return the value of order_share_info.TENANT_ID
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.TENANT_ID
     *
     * @param tenantId the value for order_share_info.TENANT_ID
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    public Integer getShareId() {
        return shareId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.SHARE_ID
     *
     * @param shareId the value for order_share_info.SHARE_ID
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */

    public void setShareId(Integer shareId) {
        this.shareId = shareId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.ORDER_NAME
     *
     * @return the value of order_share_info.ORDER_NAME
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.ORDER_NAME
     *
     * @param orderName the value for order_share_info.ORDER_NAME
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.AGE_REQUIREMENT
     *
     * @return the value of order_share_info.AGE_REQUIREMENT
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getAgeRequirement() {
        return ageRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.AGE_REQUIREMENT
     *
     * @param ageRequirement the value for order_share_info.AGE_REQUIREMENT
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setAgeRequirement(String ageRequirement) {
        this.ageRequirement = ageRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.SALARY_SITUATION
     *
     * @return the value of order_share_info.SALARY_SITUATION
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getSalarySituation() {
        return salarySituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.SALARY_SITUATION
     *
     * @param salarySituation the value for order_share_info.SALARY_SITUATION
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setSalarySituation(String salarySituation) {
        this.salarySituation = salarySituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.REMARK
     *
     * @return the value of order_share_info.REMARK
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.REMARK
     *
     * @param remark the value for order_share_info.REMARK
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.STATUS
     *
     * @return the value of order_share_info.STATUS
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.STATUS
     *
     * @param status the value for order_share_info.STATUS
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.SINGLE_REWARD
     *
     * @return the value of order_share_info.SINGLE_REWARD
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getSingleReward() {
        return singleReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.SINGLE_REWARD
     *
     * @param singleReward the value for order_share_info.SINGLE_REWARD
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setSingleReward(String singleReward) {
        this.singleReward = singleReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.add_time
     *
     * @return the value of order_share_info.add_time
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.add_time
     *
     * @param addTime the value for order_share_info.add_time
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.add_account
     *
     * @return the value of order_share_info.add_account
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.add_account
     *
     * @param addAccount the value for order_share_info.add_account
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.modify_time
     *
     * @return the value of order_share_info.modify_time
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.modify_time
     *
     * @param modifyTime the value for order_share_info.modify_time
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.modify_account
     *
     * @return the value of order_share_info.modify_account
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.modify_account
     *
     * @param modifyAccount the value for order_share_info.modify_account
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_share_info.is_usable
     *
     * @return the value of order_share_info.is_usable
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public String getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_share_info.is_usable
     *
     * @param isUsable the value for order_share_info.is_usable
     *
     * @mbggenerated Thu Mar 02 13:03:22 CST 2017
     */
    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable;
    }
}