package com.fbee.modules.mybatis.model;

public class TenantsStaffPolicyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_staff_policy.POLICY_NO
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    private String policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_staff_policy.STAFF_ID
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_staff_policy.TENANT_ID
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    private Integer tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_staff_policy.POLICY_NO
     *
     * @return the value of tenants_staff_policy.POLICY_NO
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_staff_policy.POLICY_NO
     *
     * @param policyNo the value for tenants_staff_policy.POLICY_NO
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_staff_policy.STAFF_ID
     *
     * @return the value of tenants_staff_policy.STAFF_ID
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_staff_policy.STAFF_ID
     *
     * @param staffId the value for tenants_staff_policy.STAFF_ID
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_staff_policy.TENANT_ID
     *
     * @return the value of tenants_staff_policy.TENANT_ID
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_staff_policy.TENANT_ID
     *
     * @param tenantId the value for tenants_staff_policy.TENANT_ID
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }
}