package com.fbee.modules.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class TenantsStaffsMedia implements Serializable{
   
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.ID
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.STAFF_ID
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.TYPE
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.PATH
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.IS_DEFAULT
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private String isDefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.add_time
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.add_account
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private String addAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.modify_time
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.modify_account
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private String modifyAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_staffs_media.is_usable
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	private String isUsable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.ID
	 * @return  the value of tenants_staffs_media.ID
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.ID
	 * @param id  the value for tenants_staffs_media.ID
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.STAFF_ID
	 * @return  the value of tenants_staffs_media.STAFF_ID
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.STAFF_ID
	 * @param staffId  the value for tenants_staffs_media.STAFF_ID
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.TYPE
	 * @return  the value of tenants_staffs_media.TYPE
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.TYPE
	 * @param type  the value for tenants_staffs_media.TYPE
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.PATH
	 * @return  the value of tenants_staffs_media.PATH
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.PATH
	 * @param path  the value for tenants_staffs_media.PATH
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.IS_DEFAULT
	 * @return  the value of tenants_staffs_media.IS_DEFAULT
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public String getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.IS_DEFAULT
	 * @param isDefault  the value for tenants_staffs_media.IS_DEFAULT
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.add_time
	 * @return  the value of tenants_staffs_media.add_time
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.add_time
	 * @param addTime  the value for tenants_staffs_media.add_time
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.add_account
	 * @return  the value of tenants_staffs_media.add_account
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public String getAddAccount() {
		return addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.add_account
	 * @param addAccount  the value for tenants_staffs_media.add_account
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.modify_time
	 * @return  the value of tenants_staffs_media.modify_time
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.modify_time
	 * @param modifyTime  the value for tenants_staffs_media.modify_time
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.modify_account
	 * @return  the value of tenants_staffs_media.modify_account
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public String getModifyAccount() {
		return modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.modify_account
	 * @param modifyAccount  the value for tenants_staffs_media.modify_account
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_staffs_media.is_usable
	 * @return  the value of tenants_staffs_media.is_usable
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public String getIsUsable() {
		return isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_staffs_media.is_usable
	 * @param isUsable  the value for tenants_staffs_media.is_usable
	 * @mbggenerated  Tue Mar 07 10:11:39 CST 2017
	 */
	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}

	private static final long serialVersionUID = 1L;

	
}