package com.fbee.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TradeRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_FLOW_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String tradeFlowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_TYPE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_AMOUNT
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private BigDecimal tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.COUNTER_FEE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private BigDecimal counterFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_TIME
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private Date tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_STATIS
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String tradeStatis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.INITIATOR_TYPE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String initiatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.FAILURE_MSG
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String failureMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_RESULT_CODE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String tradeResultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.is_usable
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String isUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.add_account
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.add_time
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.modify_account
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.modify_time
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.REQUEST_RESULT
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String requestResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.OUT_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String outOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_CHANNEL
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String tradeChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_records.TRADE_CHANNEL_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    private String tradeChannelNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_FLOW_NO
     *
     * @return the value of trade_records.TRADE_FLOW_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getTradeFlowNo() {
        return tradeFlowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_FLOW_NO
     *
     * @param tradeFlowNo the value for trade_records.TRADE_FLOW_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeFlowNo(String tradeFlowNo) {
        this.tradeFlowNo = tradeFlowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_TYPE
     *
     * @return the value of trade_records.TRADE_TYPE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_TYPE
     *
     * @param tradeType the value for trade_records.TRADE_TYPE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_AMOUNT
     *
     * @return the value of trade_records.TRADE_AMOUNT
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_AMOUNT
     *
     * @param tradeAmount the value for trade_records.TRADE_AMOUNT
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.COUNTER_FEE
     *
     * @return the value of trade_records.COUNTER_FEE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public BigDecimal getCounterFee() {
        return counterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.COUNTER_FEE
     *
     * @param counterFee the value for trade_records.COUNTER_FEE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setCounterFee(BigDecimal counterFee) {
        this.counterFee = counterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_TIME
     *
     * @return the value of trade_records.TRADE_TIME
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_TIME
     *
     * @param tradeTime the value for trade_records.TRADE_TIME
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_STATIS
     *
     * @return the value of trade_records.TRADE_STATIS
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getTradeStatis() {
        return tradeStatis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_STATIS
     *
     * @param tradeStatis the value for trade_records.TRADE_STATIS
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeStatis(String tradeStatis) {
        this.tradeStatis = tradeStatis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.INITIATOR_TYPE
     *
     * @return the value of trade_records.INITIATOR_TYPE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getInitiatorType() {
        return initiatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.INITIATOR_TYPE
     *
     * @param initiatorType the value for trade_records.INITIATOR_TYPE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setInitiatorType(String initiatorType) {
        this.initiatorType = initiatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.FAILURE_MSG
     *
     * @return the value of trade_records.FAILURE_MSG
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getFailureMsg() {
        return failureMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.FAILURE_MSG
     *
     * @param failureMsg the value for trade_records.FAILURE_MSG
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setFailureMsg(String failureMsg) {
        this.failureMsg = failureMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_RESULT_CODE
     *
     * @return the value of trade_records.TRADE_RESULT_CODE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getTradeResultCode() {
        return tradeResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_RESULT_CODE
     *
     * @param tradeResultCode the value for trade_records.TRADE_RESULT_CODE
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeResultCode(String tradeResultCode) {
        this.tradeResultCode = tradeResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.is_usable
     *
     * @return the value of trade_records.is_usable
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.is_usable
     *
     * @param isUsable the value for trade_records.is_usable
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.add_account
     *
     * @return the value of trade_records.add_account
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.add_account
     *
     * @param addAccount the value for trade_records.add_account
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.add_time
     *
     * @return the value of trade_records.add_time
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.add_time
     *
     * @param addTime the value for trade_records.add_time
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.modify_account
     *
     * @return the value of trade_records.modify_account
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.modify_account
     *
     * @param modifyAccount the value for trade_records.modify_account
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.modify_time
     *
     * @return the value of trade_records.modify_time
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.modify_time
     *
     * @param modifyTime the value for trade_records.modify_time
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.REQUEST_RESULT
     *
     * @return the value of trade_records.REQUEST_RESULT
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getRequestResult() {
        return requestResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.REQUEST_RESULT
     *
     * @param requestResult the value for trade_records.REQUEST_RESULT
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setRequestResult(String requestResult) {
        this.requestResult = requestResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.ORDER_NO
     *
     * @return the value of trade_records.ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.ORDER_NO
     *
     * @param orderNo the value for trade_records.ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.OUT_ORDER_NO
     *
     * @return the value of trade_records.OUT_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getOutOrderNo() {
        return outOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.OUT_ORDER_NO
     *
     * @param outOrderNo the value for trade_records.OUT_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setOutOrderNo(String outOrderNo) {
        this.outOrderNo = outOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_CHANNEL
     *
     * @return the value of trade_records.TRADE_CHANNEL
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getTradeChannel() {
        return tradeChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_CHANNEL
     *
     * @param tradeChannel the value for trade_records.TRADE_CHANNEL
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeChannel(String tradeChannel) {
        this.tradeChannel = tradeChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_records.TRADE_CHANNEL_NO
     *
     * @return the value of trade_records.TRADE_CHANNEL_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getTradeChannelNo() {
        return tradeChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_records.TRADE_CHANNEL_NO
     *
     * @param tradeChannelNo the value for trade_records.TRADE_CHANNEL_NO
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setTradeChannelNo(String tradeChannelNo) {
        this.tradeChannelNo = tradeChannelNo;
    }
}