package com.fbee.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradeRecordsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public TradeRecordsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTradeFlowNoIsNull() {
            addCriterion("TRADE_FLOW_NO is null");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoIsNotNull() {
            addCriterion("TRADE_FLOW_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoEqualTo(String value) {
            addCriterion("TRADE_FLOW_NO =", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoNotEqualTo(String value) {
            addCriterion("TRADE_FLOW_NO <>", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoGreaterThan(String value) {
            addCriterion("TRADE_FLOW_NO >", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_FLOW_NO >=", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoLessThan(String value) {
            addCriterion("TRADE_FLOW_NO <", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoLessThanOrEqualTo(String value) {
            addCriterion("TRADE_FLOW_NO <=", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoLike(String value) {
            addCriterion("TRADE_FLOW_NO like", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoNotLike(String value) {
            addCriterion("TRADE_FLOW_NO not like", value, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoIn(List<String> values) {
            addCriterion("TRADE_FLOW_NO in", values, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoNotIn(List<String> values) {
            addCriterion("TRADE_FLOW_NO not in", values, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoBetween(String value1, String value2) {
            addCriterion("TRADE_FLOW_NO between", value1, value2, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeFlowNoNotBetween(String value1, String value2) {
            addCriterion("TRADE_FLOW_NO not between", value1, value2, "tradeFlowNo");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNull() {
            addCriterion("TRADE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNotNull() {
            addCriterion("TRADE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeEqualTo(String value) {
            addCriterion("TRADE_TYPE =", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotEqualTo(String value) {
            addCriterion("TRADE_TYPE <>", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThan(String value) {
            addCriterion("TRADE_TYPE >", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE >=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThan(String value) {
            addCriterion("TRADE_TYPE <", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE <=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLike(String value) {
            addCriterion("TRADE_TYPE like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotLike(String value) {
            addCriterion("TRADE_TYPE not like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIn(List<String> values) {
            addCriterion("TRADE_TYPE in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotIn(List<String> values) {
            addCriterion("TRADE_TYPE not in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE not between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIsNull() {
            addCriterion("TRADE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIsNotNull() {
            addCriterion("TRADE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT =", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT <>", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountGreaterThan(BigDecimal value) {
            addCriterion("TRADE_AMOUNT >", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT >=", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLessThan(BigDecimal value) {
            addCriterion("TRADE_AMOUNT <", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT <=", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIn(List<BigDecimal> values) {
            addCriterion("TRADE_AMOUNT in", values, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotIn(List<BigDecimal> values) {
            addCriterion("TRADE_AMOUNT not in", values, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADE_AMOUNT between", value1, value2, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADE_AMOUNT not between", value1, value2, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andCounterFeeIsNull() {
            addCriterion("COUNTER_FEE is null");
            return (Criteria) this;
        }

        public Criteria andCounterFeeIsNotNull() {
            addCriterion("COUNTER_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andCounterFeeEqualTo(BigDecimal value) {
            addCriterion("COUNTER_FEE =", value, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeNotEqualTo(BigDecimal value) {
            addCriterion("COUNTER_FEE <>", value, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeGreaterThan(BigDecimal value) {
            addCriterion("COUNTER_FEE >", value, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COUNTER_FEE >=", value, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeLessThan(BigDecimal value) {
            addCriterion("COUNTER_FEE <", value, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COUNTER_FEE <=", value, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeIn(List<BigDecimal> values) {
            addCriterion("COUNTER_FEE in", values, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeNotIn(List<BigDecimal> values) {
            addCriterion("COUNTER_FEE not in", values, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COUNTER_FEE between", value1, value2, "counterFee");
            return (Criteria) this;
        }

        public Criteria andCounterFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COUNTER_FEE not between", value1, value2, "counterFee");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNull() {
            addCriterion("TRADE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNotNull() {
            addCriterion("TRADE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeEqualTo(Date value) {
            addCriterion("TRADE_TIME =", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotEqualTo(Date value) {
            addCriterion("TRADE_TIME <>", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThan(Date value) {
            addCriterion("TRADE_TIME >", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TRADE_TIME >=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThan(Date value) {
            addCriterion("TRADE_TIME <", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThanOrEqualTo(Date value) {
            addCriterion("TRADE_TIME <=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIn(List<Date> values) {
            addCriterion("TRADE_TIME in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotIn(List<Date> values) {
            addCriterion("TRADE_TIME not in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeBetween(Date value1, Date value2) {
            addCriterion("TRADE_TIME between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotBetween(Date value1, Date value2) {
            addCriterion("TRADE_TIME not between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeStatisIsNull() {
            addCriterion("TRADE_STATIS is null");
            return (Criteria) this;
        }

        public Criteria andTradeStatisIsNotNull() {
            addCriterion("TRADE_STATIS is not null");
            return (Criteria) this;
        }

        public Criteria andTradeStatisEqualTo(String value) {
            addCriterion("TRADE_STATIS =", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisNotEqualTo(String value) {
            addCriterion("TRADE_STATIS <>", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisGreaterThan(String value) {
            addCriterion("TRADE_STATIS >", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_STATIS >=", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisLessThan(String value) {
            addCriterion("TRADE_STATIS <", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisLessThanOrEqualTo(String value) {
            addCriterion("TRADE_STATIS <=", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisLike(String value) {
            addCriterion("TRADE_STATIS like", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisNotLike(String value) {
            addCriterion("TRADE_STATIS not like", value, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisIn(List<String> values) {
            addCriterion("TRADE_STATIS in", values, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisNotIn(List<String> values) {
            addCriterion("TRADE_STATIS not in", values, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisBetween(String value1, String value2) {
            addCriterion("TRADE_STATIS between", value1, value2, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andTradeStatisNotBetween(String value1, String value2) {
            addCriterion("TRADE_STATIS not between", value1, value2, "tradeStatis");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeIsNull() {
            addCriterion("INITIATOR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeIsNotNull() {
            addCriterion("INITIATOR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeEqualTo(String value) {
            addCriterion("INITIATOR_TYPE =", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeNotEqualTo(String value) {
            addCriterion("INITIATOR_TYPE <>", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeGreaterThan(String value) {
            addCriterion("INITIATOR_TYPE >", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("INITIATOR_TYPE >=", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeLessThan(String value) {
            addCriterion("INITIATOR_TYPE <", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeLessThanOrEqualTo(String value) {
            addCriterion("INITIATOR_TYPE <=", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeLike(String value) {
            addCriterion("INITIATOR_TYPE like", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeNotLike(String value) {
            addCriterion("INITIATOR_TYPE not like", value, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeIn(List<String> values) {
            addCriterion("INITIATOR_TYPE in", values, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeNotIn(List<String> values) {
            addCriterion("INITIATOR_TYPE not in", values, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeBetween(String value1, String value2) {
            addCriterion("INITIATOR_TYPE between", value1, value2, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andInitiatorTypeNotBetween(String value1, String value2) {
            addCriterion("INITIATOR_TYPE not between", value1, value2, "initiatorType");
            return (Criteria) this;
        }

        public Criteria andFailureMsgIsNull() {
            addCriterion("FAILURE_MSG is null");
            return (Criteria) this;
        }

        public Criteria andFailureMsgIsNotNull() {
            addCriterion("FAILURE_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andFailureMsgEqualTo(String value) {
            addCriterion("FAILURE_MSG =", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotEqualTo(String value) {
            addCriterion("FAILURE_MSG <>", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgGreaterThan(String value) {
            addCriterion("FAILURE_MSG >", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgGreaterThanOrEqualTo(String value) {
            addCriterion("FAILURE_MSG >=", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgLessThan(String value) {
            addCriterion("FAILURE_MSG <", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgLessThanOrEqualTo(String value) {
            addCriterion("FAILURE_MSG <=", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgLike(String value) {
            addCriterion("FAILURE_MSG like", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotLike(String value) {
            addCriterion("FAILURE_MSG not like", value, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgIn(List<String> values) {
            addCriterion("FAILURE_MSG in", values, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotIn(List<String> values) {
            addCriterion("FAILURE_MSG not in", values, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgBetween(String value1, String value2) {
            addCriterion("FAILURE_MSG between", value1, value2, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andFailureMsgNotBetween(String value1, String value2) {
            addCriterion("FAILURE_MSG not between", value1, value2, "failureMsg");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeIsNull() {
            addCriterion("TRADE_RESULT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeIsNotNull() {
            addCriterion("TRADE_RESULT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeEqualTo(String value) {
            addCriterion("TRADE_RESULT_CODE =", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeNotEqualTo(String value) {
            addCriterion("TRADE_RESULT_CODE <>", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeGreaterThan(String value) {
            addCriterion("TRADE_RESULT_CODE >", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_RESULT_CODE >=", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeLessThan(String value) {
            addCriterion("TRADE_RESULT_CODE <", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_RESULT_CODE <=", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeLike(String value) {
            addCriterion("TRADE_RESULT_CODE like", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeNotLike(String value) {
            addCriterion("TRADE_RESULT_CODE not like", value, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeIn(List<String> values) {
            addCriterion("TRADE_RESULT_CODE in", values, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeNotIn(List<String> values) {
            addCriterion("TRADE_RESULT_CODE not in", values, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeBetween(String value1, String value2) {
            addCriterion("TRADE_RESULT_CODE between", value1, value2, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andTradeResultCodeNotBetween(String value1, String value2) {
            addCriterion("TRADE_RESULT_CODE not between", value1, value2, "tradeResultCode");
            return (Criteria) this;
        }

        public Criteria andIsUsableIsNull() {
            addCriterion("is_usable is null");
            return (Criteria) this;
        }

        public Criteria andIsUsableIsNotNull() {
            addCriterion("is_usable is not null");
            return (Criteria) this;
        }

        public Criteria andIsUsableEqualTo(String value) {
            addCriterion("is_usable =", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableNotEqualTo(String value) {
            addCriterion("is_usable <>", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableGreaterThan(String value) {
            addCriterion("is_usable >", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableGreaterThanOrEqualTo(String value) {
            addCriterion("is_usable >=", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableLessThan(String value) {
            addCriterion("is_usable <", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableLessThanOrEqualTo(String value) {
            addCriterion("is_usable <=", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableLike(String value) {
            addCriterion("is_usable like", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableNotLike(String value) {
            addCriterion("is_usable not like", value, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableIn(List<String> values) {
            addCriterion("is_usable in", values, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableNotIn(List<String> values) {
            addCriterion("is_usable not in", values, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableBetween(String value1, String value2) {
            addCriterion("is_usable between", value1, value2, "isUsable");
            return (Criteria) this;
        }

        public Criteria andIsUsableNotBetween(String value1, String value2) {
            addCriterion("is_usable not between", value1, value2, "isUsable");
            return (Criteria) this;
        }

        public Criteria andAddAccountIsNull() {
            addCriterion("add_account is null");
            return (Criteria) this;
        }

        public Criteria andAddAccountIsNotNull() {
            addCriterion("add_account is not null");
            return (Criteria) this;
        }

        public Criteria andAddAccountEqualTo(String value) {
            addCriterion("add_account =", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountNotEqualTo(String value) {
            addCriterion("add_account <>", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountGreaterThan(String value) {
            addCriterion("add_account >", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountGreaterThanOrEqualTo(String value) {
            addCriterion("add_account >=", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountLessThan(String value) {
            addCriterion("add_account <", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountLessThanOrEqualTo(String value) {
            addCriterion("add_account <=", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountLike(String value) {
            addCriterion("add_account like", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountNotLike(String value) {
            addCriterion("add_account not like", value, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountIn(List<String> values) {
            addCriterion("add_account in", values, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountNotIn(List<String> values) {
            addCriterion("add_account not in", values, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountBetween(String value1, String value2) {
            addCriterion("add_account between", value1, value2, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddAccountNotBetween(String value1, String value2) {
            addCriterion("add_account not between", value1, value2, "addAccount");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andModifyAccountIsNull() {
            addCriterion("modify_account is null");
            return (Criteria) this;
        }

        public Criteria andModifyAccountIsNotNull() {
            addCriterion("modify_account is not null");
            return (Criteria) this;
        }

        public Criteria andModifyAccountEqualTo(String value) {
            addCriterion("modify_account =", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountNotEqualTo(String value) {
            addCriterion("modify_account <>", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountGreaterThan(String value) {
            addCriterion("modify_account >", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountGreaterThanOrEqualTo(String value) {
            addCriterion("modify_account >=", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountLessThan(String value) {
            addCriterion("modify_account <", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountLessThanOrEqualTo(String value) {
            addCriterion("modify_account <=", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountLike(String value) {
            addCriterion("modify_account like", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountNotLike(String value) {
            addCriterion("modify_account not like", value, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountIn(List<String> values) {
            addCriterion("modify_account in", values, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountNotIn(List<String> values) {
            addCriterion("modify_account not in", values, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountBetween(String value1, String value2) {
            addCriterion("modify_account between", value1, value2, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyAccountNotBetween(String value1, String value2) {
            addCriterion("modify_account not between", value1, value2, "modifyAccount");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andRequestResultIsNull() {
            addCriterion("REQUEST_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andRequestResultIsNotNull() {
            addCriterion("REQUEST_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andRequestResultEqualTo(String value) {
            addCriterion("REQUEST_RESULT =", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultNotEqualTo(String value) {
            addCriterion("REQUEST_RESULT <>", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultGreaterThan(String value) {
            addCriterion("REQUEST_RESULT >", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_RESULT >=", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultLessThan(String value) {
            addCriterion("REQUEST_RESULT <", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_RESULT <=", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultLike(String value) {
            addCriterion("REQUEST_RESULT like", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultNotLike(String value) {
            addCriterion("REQUEST_RESULT not like", value, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultIn(List<String> values) {
            addCriterion("REQUEST_RESULT in", values, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultNotIn(List<String> values) {
            addCriterion("REQUEST_RESULT not in", values, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultBetween(String value1, String value2) {
            addCriterion("REQUEST_RESULT between", value1, value2, "requestResult");
            return (Criteria) this;
        }

        public Criteria andRequestResultNotBetween(String value1, String value2) {
            addCriterion("REQUEST_RESULT not between", value1, value2, "requestResult");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoIsNull() {
            addCriterion("OUT_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoIsNotNull() {
            addCriterion("OUT_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoEqualTo(String value) {
            addCriterion("OUT_ORDER_NO =", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoNotEqualTo(String value) {
            addCriterion("OUT_ORDER_NO <>", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoGreaterThan(String value) {
            addCriterion("OUT_ORDER_NO >", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_ORDER_NO >=", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoLessThan(String value) {
            addCriterion("OUT_ORDER_NO <", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoLessThanOrEqualTo(String value) {
            addCriterion("OUT_ORDER_NO <=", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoLike(String value) {
            addCriterion("OUT_ORDER_NO like", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoNotLike(String value) {
            addCriterion("OUT_ORDER_NO not like", value, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoIn(List<String> values) {
            addCriterion("OUT_ORDER_NO in", values, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoNotIn(List<String> values) {
            addCriterion("OUT_ORDER_NO not in", values, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoBetween(String value1, String value2) {
            addCriterion("OUT_ORDER_NO between", value1, value2, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andOutOrderNoNotBetween(String value1, String value2) {
            addCriterion("OUT_ORDER_NO not between", value1, value2, "outOrderNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelIsNull() {
            addCriterion("TRADE_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andTradeChannelIsNotNull() {
            addCriterion("TRADE_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andTradeChannelEqualTo(String value) {
            addCriterion("TRADE_CHANNEL =", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNotEqualTo(String value) {
            addCriterion("TRADE_CHANNEL <>", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelGreaterThan(String value) {
            addCriterion("TRADE_CHANNEL >", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_CHANNEL >=", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelLessThan(String value) {
            addCriterion("TRADE_CHANNEL <", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelLessThanOrEqualTo(String value) {
            addCriterion("TRADE_CHANNEL <=", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelLike(String value) {
            addCriterion("TRADE_CHANNEL like", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNotLike(String value) {
            addCriterion("TRADE_CHANNEL not like", value, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelIn(List<String> values) {
            addCriterion("TRADE_CHANNEL in", values, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNotIn(List<String> values) {
            addCriterion("TRADE_CHANNEL not in", values, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelBetween(String value1, String value2) {
            addCriterion("TRADE_CHANNEL between", value1, value2, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNotBetween(String value1, String value2) {
            addCriterion("TRADE_CHANNEL not between", value1, value2, "tradeChannel");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoIsNull() {
            addCriterion("TRADE_CHANNEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoIsNotNull() {
            addCriterion("TRADE_CHANNEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoEqualTo(String value) {
            addCriterion("TRADE_CHANNEL_NO =", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoNotEqualTo(String value) {
            addCriterion("TRADE_CHANNEL_NO <>", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoGreaterThan(String value) {
            addCriterion("TRADE_CHANNEL_NO >", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_CHANNEL_NO >=", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoLessThan(String value) {
            addCriterion("TRADE_CHANNEL_NO <", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoLessThanOrEqualTo(String value) {
            addCriterion("TRADE_CHANNEL_NO <=", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoLike(String value) {
            addCriterion("TRADE_CHANNEL_NO like", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoNotLike(String value) {
            addCriterion("TRADE_CHANNEL_NO not like", value, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoIn(List<String> values) {
            addCriterion("TRADE_CHANNEL_NO in", values, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoNotIn(List<String> values) {
            addCriterion("TRADE_CHANNEL_NO not in", values, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoBetween(String value1, String value2) {
            addCriterion("TRADE_CHANNEL_NO between", value1, value2, "tradeChannelNo");
            return (Criteria) this;
        }

        public Criteria andTradeChannelNoNotBetween(String value1, String value2) {
            addCriterion("TRADE_CHANNEL_NO not between", value1, value2, "tradeChannelNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_records
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 24 15:17:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_records
     *
     * @mbggenerated Fri Feb 24 15:17:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}