package com.fbee.modules.mybatis.dao;


import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.model.OrderShareInfo;
import com.fbee.modules.mybatis.model.OrderShareInfoExample;


@MyBatisDao
public interface OrderShareInfoMapper {

    
    /**
     * 根据订单流水号获取分享信息
     */
    Map<String, Object> selectShareInfoByOrderNo(String orderNo);
    
    /**
     * 根据订单流水号获取淘蜂享信息
     */
    Map<String,Object> selectTaoShareInfoByOrderNo(String orderNo);
    
    /**
     * 根据订单流水号获取订单分享状态
     */
    String getOrderShareStatus(String orderNo);
    
    /**
     * 查询分享池中租户订单分享且订单状态是未结单
     */
    int getNumOrderInShare(Integer tenantId);

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int countByExample(OrderShareInfoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int deleteByExample(OrderShareInfoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int deleteByPrimaryKey(String orderNo);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int insert(OrderShareInfo record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int insertSelective(OrderShareInfo record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	List<OrderShareInfo> selectByExample(OrderShareInfoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	OrderShareInfo selectByPrimaryKey(String orderNo);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int updateByExampleSelective(@Param("record") OrderShareInfo record,
			@Param("example") OrderShareInfoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int updateByExample(@Param("record") OrderShareInfo record, @Param("example") OrderShareInfoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int updateByPrimaryKeySelective(OrderShareInfo record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_share_info
	 * @mbggenerated  Thu Mar 02 13:03:22 CST 2017
	 */
	int updateByPrimaryKey(OrderShareInfo record);
	/**
     * 获取蜂享池信息列�?
     * @returns
     */
	Integer getOrderShareInfoCount();
	List<Map> getOrderShareInfoList(Map<String, Object> map);
	
	/**
	 * 订单信息
	 * @param orderNo
	 * @return
	 */
	Map getOrderInfo(String orderNo);
	/**
	 * 服务信息
	 * @param orderNo
	 * @return
	 */
	Map getServiceInfo(String orderNo);
	/**
	 * 客户信息
	 * @param memberId
	 * @return
	 */
	Map getCustBaseInfo(Integer memberId);
	/**
	 * 获取阿姨列表信息
	 * @return
	 */
	Integer getStaffInfoCount();
	List<Map> getStaffInfoList(Map<String, Object> map);
	/**
	 * 获取投�?�箱信息
	 * @return
	 */
	Integer getDeliveryBoxInfoCount(Map<String, Object>  map);

	List<Map> getDeliveryBoxInfoList(Map<String, Object> map);
	/**
	 * 获取阿姨明细信息
	 * @param staffId
	 * @return
	 */
	Map getStaffBaseInfo(Integer staffId);
	Map getStaffJobInfo(Integer staffId);
	
	/**
	 * 获取订单分享阿姨信息
	 * @return
	 */
	Map getOrderShareStaffInfo(Map paramMap);

	/**
	 * 根据订单流水号获取分享信息
	 */
	// @xiehui
	Map<String, Object> selectShareInfoByOrderNo(Map<String, Object> map);

}