package com.fbee.modules.mybatis.dao;

import java.util.List;
import java.util.Map;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.OrdersEntity;
import com.fbee.modules.mybatis.entity.ReserveOrdersEntity;
import com.fbee.modules.mybatis.model.Orders;
import com.fbee.modules.mybatis.model.OrdersExample;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface OrdersMapper extends CrudDao<OrdersEntity>{
	
	/**
	 * 获取订单条数
	 */
	int getCount(OrdersEntity entity);
	
	/**
	 * 订单列表查询
	 * @param entity
	 * @return
	 */
	@SuppressWarnings("rawtypes")
	List<Map> selectOrdersList(OrdersEntity entity);
	
	/**
	 * 根据订单流水号查询订单信息
	 * @param orderNo
	 * @return
	 */
	Map<String, Object> selectByOrderNo(String orderNo);
	
	/**
	 * 根据订单流水号查询支付信息
	 * @param orderNo
	 * @return
	 */
	Map<String, Object> selectPayInfoByOrderNo(String orderNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int countByExample(OrdersExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int deleteByExample(OrdersExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int deleteByPrimaryKey(String orderNo);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int insert(Orders record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int insertSelective(Orders record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	List<Orders> selectByExample(OrdersExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	Orders selectByPrimaryKey(String orderNo);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int updateByPrimaryKeySelective(Orders record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Tue Feb 28 17:31:39 CST 2017
	 */
	int updateByPrimaryKey(Orders record);
	/**
	 * @param staffId
	 * @return
	 */
	List<Orders> getStaffOrders(Integer staffId);

	/**
	 * 根据订单号获取订单阿姨详情信息
	 * @param orderNo
	 * @return
	 */
    Map<String, Object> selectStaffInfoByOrderNo(String orderNo); 

	/**
	 * 查询订单超时
	 * @return
	 */
	List<Orders> selectOrderOverTime();

	/**
	 * 
	 */
	List<Orders> getStaffWorkList(Integer staffId);


	/**
	 * 本地订单-定金支付
	 * @param orders
	 * author Baron
	 * date 2017-04-27
	 * @return
	 */
	int updatedepositPaystate(Orders orders);


	/**
	 * 本地订单-定金修改
	 * @param orders
	 * author Baron
	 * date 2017-04-27
	 * @return
	 */
	int modifyDeposit(Orders orders);
	/**
	 * 根据状态取消订单
	 * @xiehui
	 * @param map
	 * @return
	 */
	int cancelOrderStatus(Map<String, Object> map);

	/**
	 * 修改订单状态
	 * @xiehui
	 * @param map
	 * @return
	 */
	int updateOrderState(Map<String, Object> map);

	/**
	 * @author xiehui
	 * @param orderNo
	 * @return
	 */
	int updateShareId(Orders orders);

	/**
	 * 订单-更新服务信息
	 * @param reserveOrderDetailsForm
	 * @return
	 */
	int updateByPrimaryKeySelective1(Orders orders);

}