package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.TenantsStaffPolicyEntity;
import com.fbee.modules.mybatis.model.TenantsStaffPolicy;
import com.fbee.modules.mybatis.model.TenantsStaffPolicyExample;
import com.fbee.modules.mybatis.model.TenantsStaffPolicyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TenantsStaffPolicyMapper extends CrudDao<TenantsStaffPolicyEntity>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int countByExample(TenantsStaffPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int deleteByExample(TenantsStaffPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int deleteByPrimaryKey(TenantsStaffPolicyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int insert(TenantsStaffPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int insertSelective(TenantsStaffPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    List<TenantsStaffPolicy> selectByExample(TenantsStaffPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    TenantsStaffPolicy selectByPrimaryKey(TenantsStaffPolicyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") TenantsStaffPolicy record, @Param("example") TenantsStaffPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int updateByExample(@Param("record") TenantsStaffPolicy record, @Param("example") TenantsStaffPolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int updateByPrimaryKeySelective(TenantsStaffPolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_staff_policy
     *
     * @mbggenerated Fri Feb 24 15:20:21 CST 2017
     */
    int updateByPrimaryKey(TenantsStaffPolicy record);
    
    /**
	 * 根据唯一键值获取阿姨银保单信息
	 * @param staffPolicyKey
	 * @return
	 */
	TenantsStaffPolicyEntity getPolicyInfoByKey(TenantsStaffPolicyKey staffPolicyKey);

	/**
	 * @param staffPolicyParams
	 * @return
	 */
	List<TenantsStaffPolicyEntity> getPolicyList(TenantsStaffPolicyEntity staffPolicyParams);
    
}