package com.fbee.modules.mybatis.dao;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.TenantsFinanceRecordsEntity;
import com.fbee.modules.mybatis.model.TenantsFinanceRecords;
import com.fbee.modules.mybatis.model.TenantsFinanceRecordsExample;
@MyBatisDao
public interface TenantsFinanceRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int countByExample(TenantsFinanceRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int deleteByExample(TenantsFinanceRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int deleteByPrimaryKey(String inOutNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int insert(TenantsFinanceRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int insertSelective(TenantsFinanceRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    List<TenantsFinanceRecords> selectByExample(TenantsFinanceRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    TenantsFinanceRecords selectByPrimaryKey(String inOutNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") TenantsFinanceRecords record, @Param("example") TenantsFinanceRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int updateByExample(@Param("record") TenantsFinanceRecords record, @Param("example") TenantsFinanceRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int updateByPrimaryKeySelective(TenantsFinanceRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_finance_records
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    int updateByPrimaryKey(TenantsFinanceRecords record);

	Integer getCountById(TenantsFinanceRecordsEntity tenantsFinanceRecordsEntity);

	List<Map> getByTenantsId(TenantsFinanceRecordsEntity tenantsFinanceRecordsEntity);
	//添加阿姨财务记录
	int insertFinancialRecord(TenantsFinanceRecords tenantsFinanceRecords);

	List<TenantsFinanceRecords> getStaffFinances(Map<String,Object> map);
	
	//查询小计，收支总数
	Integer getInCountById(TenantsFinanceRecordsEntity tenantsFinanceRecordsEntity);
	Integer getOutCountById(TenantsFinanceRecordsEntity tenantsFinanceRecordsEntity);
	//收支金额
	BigDecimal getInAmountById(TenantsFinanceRecordsEntity tenantsFinanceRecordsEntity);
	BigDecimal getOutAmountById(TenantsFinanceRecordsEntity tenantsFinanceRecordsEntity);
}