package com.fbee.modules.mybatis.dao;

import java.util.List;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.TenantsAboutUsEntity;
import com.fbee.modules.mybatis.model.TenantsAboutUs;
import com.fbee.modules.mybatis.model.TenantsAboutUsExample;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TenantsAboutUsMapper extends CrudDao<TenantsAboutUsEntity>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int countByExample(TenantsAboutUsExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int deleteByExample(TenantsAboutUsExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int insert(TenantsAboutUs record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int insertSelective(TenantsAboutUs record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	List<TenantsAboutUs> selectByExample(TenantsAboutUsExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	TenantsAboutUs selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TenantsAboutUs record,
			@Param("example") TenantsAboutUsExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int updateByExample(@Param("record") TenantsAboutUs record, @Param("example") TenantsAboutUsExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int updateByPrimaryKeySelective(TenantsAboutUs record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_about_us
	 * @mbggenerated  Thu Mar 09 15:06:40 CST 2017
	 */
	int updateByPrimaryKey(TenantsAboutUs record);
	
	/**
	 * 获取关于我们图文信息
	 * @param tenantId
	 * @return
	 */
	TenantsAboutUs getAboutUsInfo(Integer tenantId);
	
	/**
	 * 
	 * @MethodName:updateAboutUsInfoByEntity
	 * @Type:TenantsAboutUsMapper
	 * @Description:更新 关于我们信息
	 * @Return:int
	 * @Param:@param tEntity
	 * @Param:@return
	 * @Thrown:
	 * @Date:Sep 15, 2017 2:18:43 PM
	 */
	int updateAboutUsInfoByEntity(TenantsAboutUsEntity tEntity);
}