package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.TradeRecordsEntity;
import com.fbee.modules.mybatis.model.TradeRecords;
import com.fbee.modules.mybatis.model.TradeRecordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TradeRecordsMapper extends CrudDao<TradeRecordsEntity>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int countByExample(TradeRecordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int deleteByExample(TradeRecordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int deleteByPrimaryKey(String tradeFlowNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int insert(TradeRecords record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int insertSelective(TradeRecords record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	List<TradeRecords> selectByExample(TradeRecordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	TradeRecords selectByPrimaryKey(String tradeFlowNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TradeRecords record, @Param("example") TradeRecordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int updateByExample(@Param("record") TradeRecords record, @Param("example") TradeRecordsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int updateByPrimaryKeySelective(TradeRecords record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated  Fri Feb 24 15:17:17 CST 2017
	 */
	int updateByPrimaryKey(TradeRecords record);
}